### ISSUE TITLE
TDD Todo Services

### ISSUE THREAD

**Issue by karudedios** [karudedios/todo-angular-js#6]
- As a developer I'd like to have Todo services and interactors to guide me in the model design labor.

**AC**
- TDD Services for
  - [x] Creation of Todos
  - [ ] Updating of Todos
  - [x] Deletion of Todos
  - [ ] Fetching single Todo
